### ISSUE TITLE
Error when using Emacs versions < 28

### ISSUE THREAD

**Issue by a-wilhelm** [jobbflykt/x509-mode#11]
Using Emacs version < 28, this
https://github.com/jobbflykt/x509-mode/blob/49fbab6166d03e5d4c8b856de6ef04b99ba16eb4/x509-mode.el#L405-L407

fails because the second optional argument to `generate-new-buffer` was added in 28. From /etc/NEWS.28:
```
** Buffers can now be created with certain hooks disabled.
The functions 'get-buffer-create' and 'generate-new-buffer' accept a
new optional argument INHIBIT-BUFFER-HOOKS.  If non-nil, the new
buffer does not run the hooks 'kill-buffer-hook',
'kill-buffer-query-functions', and 'buffer-list-update-hook'.  This
avoids slowing down internal or temporary buffers that are never
presented to users or passed on to other applications.
```
However package indicates compatibility with 24.3:
`(define-package "x509-mode" "20220705.757" "View certificates, CRLs and keys using OpenSSL"
  '((emacs "24.3"))
`

**Comment by jobbflykt** [comment]
Right. I'm unsure how to fix this properly. It seems overly constrictive to require emacs 28 and I'm reluctant to introduce code that checks if that parameter is available or not. The INHIBIT-BUFFER-HOOKS parameter is not at all important for x509-mode, just a nice touch. So I think I will just remove it.
