### ISSUE TITLE
Is there a license?

### ISSUE THREAD

**Issue by dcunited001** [jobbflykt/x509-mode#12]
I'm packaging this up for a personal guix channel. is there a license for this software?

i've started building this [usb-gpg-tool.scm](https://github.com/dcunited001/ellipsis/blob/master/ellipsis/systems/usb-gpg-tool.scm) image for managing a small homelab CA on an airgapped computer. it's based on the Nix image at [drduh/YubiKeyGuide](https://github.com/drduh/YubiKeyGuide). this is very helpful for learning certs, but i need it to be a Guix package to include it on the image. 

i may submit a patch request to guix, but i still need to setup GPG and etc, so it may be some time.

**Comment by jobbflykt** [comment]
Thanks for pointing this out. Added LICENSE.md with MIT license.
